version: '2'

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - wp_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=uwm-wordpress
      - MYSQL_DATABASE=uwm-wordpress
      - MYSQL_USER=uwm-wordpress
      - MYSQL_PASSWORD=uwm-wordpress
    expose:
      - 3306
      - 33060
  wordpress-test:
    build:
      dockerfile: Dockerfile
    image: wordpress:latest
    volumes:
      - ~/CodeExperiments/dev-containers/wordpress/themes:/var/www/html/wp-content/themes
      - ~/CodeExperiments/dev-containers/wordpress/plugins:/var/www/html/wp-content/plugins
      - ~/CodeExperiments/dev-containers/wordpress/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ~/CodeExperiments/dev-containers/wordpress/wp-config.php:/var/www/html/wp-config.php
    #ports:
    #  - 7122:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=uwm-wordpress
      - WORDPRESS_DB_PASSWORD=uwm-wordpress
      - WORDPRESS_DB_NAME=uwm-wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-test.rule=Host(`wp-test.localhost`)"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'wp-test.localhost:host-gateway'
    networks:
      - proxy
      - backend
volumes:
  wp_data:

networks:
  proxy:
    external: true
  backend:

